apiVersion: 1.0.0                            

previews:
  - name: helm
    helm:
      chart: ./charts/mnaut-demo/
      valuesFiles: 
      values: 
        image: 
          repository: caladreas/mnaut-demo
          tag: 0.1.${ENV_COMMIT_SHA}
        preview:
          enabled: true
        ingress:
          host: ${ENV_HOSTNAME}
          tlsSecretName: ${ENV_TLS_SECRET_NAME}
        instanceName: ${ENV_UNIQUE_NAME}
