{{- if .Values.preview }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    {{- if .Values.service.name }}
    app: {{ .Values.service.name }}
    {{- else }}
    app: {{ template "fullname" . }}
  {{- end }}
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                {{- if .Values.service.name }}
                name: {{ .Values.service.name }}
                {{- else }}
                name: {{ template "fullname" . }}
                {{- end }}
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
