name: GraalVM CE CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get HEAD SHA
        run: echo "PR_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Verify HEAD SHA
        run: echo "PR_SHA=${PR_SHA}"
      - name: Test2
        run: echo $PR_SHA
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $PR_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT        
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.2.0.java11
      - name: Install Native Image
        run: gu install native-image
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract GAV
        id: extract
        uses: andreacomo/maven-gav-extractor@v1
      - name: Log GAV
        run: |
          echo ${{ steps.extract.outputs.group-id }}
          echo ${{ steps.extract.outputs.artifact-id }}
          echo ${{ steps.extract.outputs.version }}
        shell: bash          
      - name: Build And Push Docker Image
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_REPOSITORY_PATH}/mnaut-demo" | sed -e 's#//#/#' -e 's#^/##'`
          ./mvnw deploy -Dpackaging=docker-native -Djib.docker.image=$DOCKER_IMAGE --no-transfer-progress -Drevision=${{ steps.extract.outputs.version }}.${PR_SHA} 
